# Generated by Django 2.2.1 on 2019-05-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandloadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('landload_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('landload_address', models.CharField(max_length=30)),
                ('rent_date', models.DateField()),
                ('rent_price', models.IntegerField()),
                ('electric_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('water_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('network_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('key_number', models.IntegerField()),
                ('air_condition', models.BooleanField()),
                ('washing_machine', models.BooleanField()),
                ('rental_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Rental_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_phone_number', models.CharField(max_length=20)),
                ('rent_Date', models.DateField()),
                ('rent_price', models.IntegerField()),
                ('electric_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('water_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('network_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('key_number', models.IntegerField()),
                ('air_condition', models.BooleanField()),
                ('washing_machine', models.BooleanField()),
                ('pay_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RentHouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('cur_address', models.CharField(max_length=30)),
                ('write_interview', models.CharField(max_length=50)),
                ('house_image', models.ImageField(upload_to='img')),
                ('house_price', models.IntegerField()),
            ],
        ),
    ]
