# Generated by Django 2.2.1 on 2019-06-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190624_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentalinfo',
            old_name='rent_phone_number',
            new_name='rent_phone',
        ),
    ]
